/* eslint-disable max-len */
export const GAMES_CH8 = [
  {
    name: 'Tetris',
    code: 'data:application/octet-stream;base64,orQj5iK2cAHQETAlEgZx/9ARYBrQEWAlMQASDsRwRHASHMMDYB5hAyJc9RXQFD8BEjzQFHH/0BQjQBIc56EicuihIoTpoSKW4p4SUGYA9hX2BzYAEjzQFHEBEiqixPQeZgBDAWYEQwJmCEMDZgz2HgDu0BRw/yM0PwEA7tAUcAEjNADu0BRwASM0PwEA7tAUcP8jNADu0BRzAUMEYwAiXCM0PwEA7tAUc/9D/2MDIlwjNADugABnBWgGaQRhH2UQYgcA7kDgAABAwEAAAOBAAEBgQABAQGAAIOAAAMBAQAAA4IAAQEDAAADgIABgQEAAgOAAAEDAgADAYAAAQMCAAMBgAACAwEAAAGDAAIDAQAAAYMAAwMAAAMDAAADAwAAAwMAAAEBAQEAA8AAAQEBAQADwAADQFGY1dv82ABM4AO6itIwQPB58ATwefAE8HnwBI15LCiNykcAA7nEBE1BgG2sA0BE/AHsB0BFwATAlE2IA7mAb0BFwATAlE3SOEI3gfv9gG2sA0OE/ABOQ0OETlNDRewFwATAlE4ZLABOmff9+/z0BE4IjwD8BI8B6ASPAgKBtB4DSQAR1/kUCZQQA7qcA8lWoBPoz8mXwKW0ybgDd5X0F8Snd5X0F8ind5acA8mWitADuagBgGQDuNyM=',
    description: '4 - Rotate<br />5 - Left<br/>6 - Right<br />7 - Fast',
  },
  {
    name: 'TicTacToe',
    code: 'data:application/octet-stream;base64,EhhUSUNUQUMgYnkgRGF2aWQgV0lOVEVSawBsAICwgcCj5vFVo8T/ZaO0/1Wj5vFliwCMEADgbgFgE2EDo5rQEXAIMCsSPmATcQgxIxI+YBNhA6Ob0B9wCDAzElRgE3EP0BpwCDAzEmAjZvAKgQCjtPAe8GVAABKKInwSamAQ8BjwFfAHMAASggDuYAKOA4Dg8FWj1IAQcP+ABPAe8WWjqj4Do6/QFSLIOgASHKO0YQBiAGMB8GUwAHEB8x5yATIQErQxEBJqEhxqAKO0YAHwHvhlaQCJBCNEiRQjRIkkI0ppAIk0I0SJRCNEiVQjSmkAiWQjRIl0I0SJhCNKaQCJZCNEiTQjRIkEI0ppAIl0I0SJRCNEiRQjSmkAiYQjRIlUI0SJJCNKaQCJhCNEiUQjRIkEI0ppAIlkI0SJRCNEiSQjSgDuiQ6JDgDuSRUTVEk/E1oA7iNmewETXiNmfAEjZmoB8AoA7mMFZAqjr9NFYwJ0BqPm+zMjiGMyZAqjqtNFYy90BqPm/DPyZfApI5TxKSOU8inTRXMFAO5/gICAgICAgICAgICAgICAHCIiIhwiFAgUIgEAAAAAAAAAAAABAQEBAQEBAAAAAAAAAAAAAQEBAQEBEwUbBSMFEw0bDSMNExUbFSMV',
    description: '1-9 - Each cell.',
  },
  {
    name: 'Ponk',
    code: 'data:application/octet-stream;base64,agJrDGw/bQyi6tq23NZuACLUZgNoAmBg8BXwBzAAEhrHF3cIaf+i8NZxourattzWYAHgoXv+YATgoXsCYB+LAtq2YAzgoX3+YA3goX0CYB+NAtzWovDWcYaEh5RgP4YCYR+HEkYCEnhGPxKCRx9p/0cAaQHWcRIqaAJjAYBwgLUSimj+YwqAcIDVPwESomECgBU/ARK6gBU/ARLIgBU/ARLCYCDwGCLUjjQi1GY+MwFmA2j+MwFoAhIWef9J/mn/Esh5AUkCaQFgBPAYdgFGQHb+Emyi8v4z8mXxKWQUZQDUVXQV8inUVQDugICAgICAgAAAAAAA',
    description: 'Player 1:<br />2 - up 4 - down<br /><br />Player 2:<br />A - up 0 - down',
  },
  {
    name: 'Test',
    code: 'data:application/octet-stream;base64,Ek7qrKrqzqqqruCgoODAQEDg4CDA4OBgIOCg4CAgYEAgQOCA4ODgICAg4OCg4ODgIOBAoOCg4MCA4OCAwICgQKCgogLatADuogLatBPcaAFpBWoKawFlKmYrohbYtKI+2bSiAjYrogbatGsGohrYtKI+2bSiBkUqogLatGsLoh7YtKI+2bSiBlVgogLatGsQoibYtKI+2bSiBnb/RiqiAtq0axWiLti0oj7ZtKIGlWCiAtq0axqiMti0oj7ZtCJCaBdpG2ogawGiCti0ojbZtKIC2rRrBqIq2LSiCtm0ogaHUEcqogLatGsLoirYtKIO2bSiBmcqh7FHK6IC2rRrEKIq2LSiEtm0ogZmeGcfh2JHGKIC2rRrFaIq2LSiFtm0ogZmeGcfh2NHZ6IC2rRrGqIq2LSiGtm0ogZmjGeMh2RHGKIC2rRoLGkwajRrAaIq2LSiHtm0ogZmjGd4h2VH7KIC2rRrBqIq2LSiItm0ogZm4IZuRsCiAtq0awuiKti0ojbZtKIGZg+GZkYHogLatGsQojrYtKIe2bSj6GAAYTDxVaPp8GWiBkAwogLatGsVojrYtKIW2bSj6GaJ9jPyZaICMAGiBjEDogYyB6IG2rRrGqIO2LSiPtm0EkgT3A==',
    description: '',
  },
];
